### PR TITLE
Ignore parted warnings if possible

### LINKED ISSUE #214: Parted warning is treated as an error
Currently any parted exception is treated as an error (which leads to abort). A parted exception may be only a warning and it should be treated as such in that case.

I would love to work on a PR to fix this.

I'm not sure how warnings should be treated in this library and therefore suggestions are welcome.

Furthermore this issue is a question on whether PRs on this are welcome at all.

### PR DESCRIPTION
**Pull request by squimrel**
Ignore parted exceptions of type warning and information if parted marks them as ignorable. Fixes #214.

~~I haven't tested this yet \*cough*. Plus I should probably add at least one test case in which a parted warning is ignored. So please don't merge yet.~~

### CODE REVIEW

File: src/plugins/part_err.c [hunk 1]
```diff
@@ -24,8 +24,16 @@
 static __thread gchar *error_msg = NULL;
 
 PedExceptionOption bd_exc_handler (PedException *ex) {
-    error_msg = g_strdup (ex->message);
-    return PED_EXCEPTION_UNHANDLED;
+    /*
+     * Only treat exceptions as errors if they aren't at least errors or can't
+     * be ignored.
+     */
```
Comment (squimrel) [inline src/plugins/part_err.c]: This comment seems pretty superfluous to me.

**Comment by squimrel** [comment]
This seems to work but I have a hard time creating a test that throws a parted warning so I'd think about giving up on it. Current tests still pass.

File: src/plugins/part_err.c (hunk 1 above)
Comment (vpodzime) [inline src/plugins/part_err.c]: ``aren't`` should be ``are``, shouldn't it?

File: src/plugins/part_err.c [hunk 2]
```diff
@@ -17,15 +17,24 @@
...
+    if (ex->type >= PED_EXCEPTION_ERROR || (ex->options & PED_EXCEPTION_IGNORE) == 0) {
+      error_msg = g_strdup (ex->message);
+      return PED_EXCEPTION_UNHANDLED;
+    }
+    g_warning ("[parted] %s", ex->message);
+    return PED_EXCEPTION_IGNORE;
```
Comment (vpodzime) [inline src/plugins/part_err.c]: I'd prefer if the logic was inverted here. So something like ``if THIS_CAN_BE_IGNORED -> ignore; else raise``

**Comment by squimrel** [comment]
There you go.

**Comment by vpodzime** [comment]
Jenkins, this is ok to test.
